repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml


  - repo: git@github.com:Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        name: Tabs remover
        args: [--whitespaces-count, '4']

  - repo: git@github.com:psf/black-pre-commit-mirror.git
    rev: 25.1.0
    hooks:
      - id: black

  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]

  - repo: git@github.com:Yelp/detect-secrets.git
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: git@github.com:PyCQA/bandit.git
    rev: 1.8.5
    hooks:
      - id: bandit

  - repo: git@github.com:commitizen-tools/commitizen.git
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
